---
- hosts: all
  tasks:
  - name: install example application
    copy:
      src: test_app
      dest: /tmp
      owner: root
      group: root
  - name: run example app
    shell: /tmp/test/app.sh
