---
- hosts: all
  tasks:
  - name: install example application
    copy:
      src: test_app
      dest: /tmp
      owner: root
      group: root
      mode: preserve
  - name: run example app
    shell: chmod +x /tmp/test_app/app.sh && /tmp/test_app/app.sh
